/* important file for gajendra story html starts*/
let story=document.querySelector(".mhrstory");

let box=document.querySelector(".box");

let hstory=document.querySelector(".headingofstory");

/* important file for gajendra story html ends*/

box.addEventListener("click",()=>{
    if(box.innerText=="English"){
    box.innerHTML="<div class='box' style='justify-content:flex-end;'>हिन्दी<div class='dot'style='margin-left:20%;'></div></div>";
    hstory.innerText="हवलदार गजेंद्र सिंह";
    story.innerHTML="<p>देहरादून, उत्तराखंड के सुंदर नगर में, 1 जुलाई 1972 को एक नायक ने जन्म लिया। हवलदार गजेंद्र सिंह बिष्ट, एक ऐसा नाम जो बहादुरी और बलिदान का पर्याय बन गया, ने गणेशपुर गांव की शांतिपूर्ण वादियों में अपनी पहली सांस ली।<br><br> <img src='nsg.jpeg' alt='gajendra singh'><br><br>बचपन से ही गजेंद्र की कर्तव्यपरायणता और देशभक्ति की भावना ने उन्हें भारतीय सेना में शामिल होने के लिए प्रेरित किया। वह अपने देश की सेवा करने और इसके लोगों की रक्षा करने के लिए दृढ़संकल्प थे। उनकी समर्पण और लगन ने उन्हें राष्ट्रीय सुरक्षा गार्ड (NSG) की विशिष्ट इकाई में स्थान दिलाया, जिसे आतंकवाद-रोधी अभियानों के लिए विशेष रूप से प्रशिक्षित किया जाता है<br><br>26 नवंबर 2008 की रात थी, और मुंबई शहर आतंकवादियों के हमले का शिकार था। आतंकवादियों ने दक्षिण मुंबई की कई प्रसिद्ध इमारतों, जिनमें यहूदी केंद्र नरीमन हाउस भी शामिल था, पर कब्जा कर लिया। उन्होंने कई निर्दोष लोगों को बंधक बना लिया और उन्हें दो दिनों तक चलने वाली भयानक त्रासदी का सामना करना पड़ा।<br><br>हवलदार गजेंद्र सिंह, राष्ट्रीय सुरक्षा गार्ड की 51 स्पेशल एक्शन ग्रुप के बहादुर सदस्य, इस संकट को सुलझाने के लिए तैनात टीम का हिस्सा थे। अपने साथी एनएसजी कमांडो के साथ, हवलदार गजेंद्र सिंह को हेलीकॉप्टर से नरीमन हाउस की छत पर उतारा गया। उनका मिशन आतंकवादियों को निष्क्रिय करना और बंधकों को बचाना था।<br><br><img src='bg.jpg' alt='commando mask'><br><br>हवलदार गजेंद्र सिंह के नेतृत्व में, टीम ने 14 नागरिकों को सफलतापूर्वक बचाकर सुरक्षित स्थानों पर पहुंचाया। लेकिन मिशन अभी समाप्त नहीं हुआ था। हवलदार गजेंद्र सिंह ने आतंकवादियों का सामना करने के लिए आगे बढ़ने का निर्णय लिया। उन्होंने देखा कि एक आतंकवादी भागने की कोशिश कर रहा है और उस पर गोली चलाई। हालांकि, एक अन्य आतंकवादी ने ग्रेनेड फेंका, जिससे हवलदार गजेंद्र सिंह गंभीर रूप से घायल हो गए।<br><br>अपने घावों के बावजूद, हवलदार गजेंद्र सिंह ने हार नहीं मानी।उन्होंने महसूस किया कि उनकी टीम को स्थिति पर नियंत्रण पाने के लिए यह अवसर भुनाना होगा, और वह आतंकवादियों पर गोलियां चलाते हुए आगे बढ़ते रहे। उनके साहसिक कृत्य और अदम्य भावना ने उनके साथियों को आतंकवादियों को समाप्त करने और मिशन को सफलतापूर्वक पूरा करने के लिए प्रेरित किया।<br><br><img src='commando 2.jpg' alt='commando 2'><br><br>हवलदार गजेंद्र सिंह की बहादुरी ने उन्हें भारी कीमत चुकाने पर मजबूर किया। उन्होंने अपने घावों के कारण प्राण त्याग दिए, लेकिन उनका बलिदान कभी भुलाया नहीं जाएगा। उन्हें उनकी असाधारण बहादुरी, अदम्य साहस और सर्वोच्च बलिदान के लिए मरणोपरांत अशोक चक्र, देश का सर्वोच्च शांतिकालीन वीरता पुरस्कार, प्रदान किया गया। हवलदार गजेंद्र सिंह के परिवार में उनकी पत्नी विनिता देवी, बेटी प्रीति और बेटा गौरव हैं, जो उनके पीछे रह गए।<br><br></p>"
    
}
else{
    box.innerHTML="<div class='box' ><div class='dot'></div>English</div>";
    hstory.innerText="Hawaldar Gajendra Singh ";
    story.innerHTML="   <p class='mhrstory'>          In the picturesque town of Dehradun, Uttarakhand, a hero was born on July 1, 1972. Havaldar Gajendra Singh Bisht, a name that would become synonymous with bravery and sacrifice, took his first breath in the quaint village of Ganeshpur.<br><br>       <img src='nsg.jpeg' alt='gajendra singh'><br><br>As he grew up, Gajendra's strong sense of duty and patriotism led him to join the Indian Army. He was determined to serve his country and protect its people. His dedication and perseverance earned him a place in the elite National Security Guard (NSG), a special forces unit tasked with counter-terrorism operations.<br><br>It was the night of November 26, 2008, and the city of Mumbai was under attack. Terrorists had stormed several iconic buildings in South Mumbai, including the Jewish center of Nariman House. The terrorists took many innocent people hostage, subjecting them to a traumatic ordeal that would last for two days.<br><br>Hav Gajendra Singh, a brave member of the National Security Guard's 51 Special Action Group, was part of the team tasked with resolving this crisis. Along with his fellow NSG commandos, Hav Gajendra Singh was airdropped from a helicopter onto the roof of Nariman House. Their mission was to neutralize the terrorists and rescue the hostages.<br><br><img src='bg.jpg' alt='commando mask'><br><br>Under Hav Gajendra Singh's leadership, the team successfully extricated 14 civilians, transporting them to safer locations. But the mission was far from over. Hav Gajendra Singh moved to confront the terrorists, who were positioned to engage the assault team. He spotted one terrorist attempting to flee and fired at him. However, another terrorist hurled a grenade, seriously wounding Hav Gajendra Singh.<br><br>Despite his injuries, Hav Gajendra Singh refused to back down. He realized that his team needed to seize the opportunity to dominate the situation, and he continued moving forward, firing at the terrorists. His courageous act and unyielding spirit inspired his comrades to eliminate the terrorists and complete the mission successfully.<br><br><img src='commando 2.jpg' alt='commando 2'><br><br>Hav Gajendra Singh's bravery came at a great cost. He succumbed to his injuries, but his sacrifice will never be forgotten. He was posthumously awarded the Ashok Chakra, the nation's highest peacetime gallantry award, for his exceptional bravery, indomitable spirit, and supreme sacrifice. Hav Gajendra Singh is survived by his wife Vinita Devi, daughter Preeti, and son Gaurav.<br><br></p>"
    
}
})
