/* important file for mhr story html starts*/
let mhrstory=document.querySelector(".mhrstory");

let box=document.querySelector(".box");

let hstory=document.querySelector(".headingofstory");

/* important file for mhr story html ends*/

box.addEventListener("click",()=>{
    if(box.innerText=="English"){
    box.innerHTML="<div class='box' style='justify-content:flex-end;'>हिन्दी<div class='dot'style='margin-left:20%;'></div></div>";
    hstory.innerText="मेजर जवाहर सिंह महार ";
    mhrstory.innerHTML="<p class='mhrstory'>मेजर जवाहर सिंह महार का जन्म 29 दिसंबर 1921को मस्पतीनामक एक छोटे से गाँव में हुआ था, जो उत्तराखंड के पिथौरागढ़ जिले में स्थित है। उनके पिता, श्री जोगा सिंह ने उन्हें ऐसे मूल्यों के साथ पाला जो उन्हें महानता प्राप्त करने में मदद करेंगे। एक युवा उम्र से, महार ने एक सेना अधिकारी के रूप में अपने देश की सेवा करने की एक मजबूत इच्छा को संजोया था<br><br><img src='mhr.jpg' alt='Jawahar Singh Mahar'class='images'><br>महार का सपना तब साकार हुआ जब उन्होंने 29 मई 1943 को केवल 21 वर्ष की आयु में प्रतिष्ठित 1 पैरा (कुमाऊं) बटालियन में दूसरे लेफ्टिनेंट के रूप में शामिल हुए। उनकी असाधारण सेवा ने उन्हें केवल पांच वर्षों में मेजर के पद पर पदोन्नत करने के लिए प्रेरित किया। महार की बहादुरी और नेतृत्व का परीक्षण 1947-48 के भारत-पाकिस्तान युद्ध के दौरान हुआ, जहां उन्होंने श्रीनगर हवाई क्षेत्र की रक्षा और पुंछ की घेराबंदी में एक महत्वपूर्ण भूमिका निभाई।<br><br>मेजर जवाहर सिंह महार की बहादुरी की कहानी एक ऐसी कहानी है जो उनकी अटूट बहादुरी और देश के प्रति समर्पण को दर्शाती है।<br><br>अक्टूबर 1947 में, 1 पैरा (कुमाऊं) बटालियन, जिसका मेजर महार हिस्सा थे, जम्मू-कश्मीर में तैनात की गई थी ताकि वह पहली भारतीय सेना गठन का हिस्सा बन सके। बटालियन ने श्रीनगर हवाई क्षेत्र की रक्षा में महत्वपूर्ण भूमिका निभाई थी, जो पाकिस्तानी सेना द्वारा आक्रमण के तहत था।<br><br>एक साल बाद, जून 1948 में, मेजर महार की यूनिट को फिर से जम्मू-कश्मीर में तैनात किया गया ताकि वह पाकिस्तानी सेना का सामना कर सके। 15 जून 1948 की रात, मेजर महार के नेतृत्व में एक कॉलम ने राजौरी से आने वाले एक अन्य कॉलम से जुड़ने के लिए एक मिशन पर निकला। योजना के अनुसार, वे सम्होत में मिलने वाले थे, लेकिन रास्ते में उन्हें दुश्मन के पैट्रोल से सामना हुआ।<br><br>बिना हिचकिचाहट, मेजर महार ने खुद को पाकिस्तानी सैनिक के रूप में प्रस्तुत किया और अपनी कंपनी को दुश्मन की स्थिति से केवल 20 गज की दूरी पर ले आए। हालांकि, उनके गाइड, एक स्थानीय नागरिक ने अनजाने में उनकी सच्चाई का खुलासा कर दिया, जिससे मेजर महार और उनके सैनिकों के लिए एक जोखिम भरी स्थिति उत्पन्न हो गई।<br><br><img src='bayonet.jpeg' alt='bayonet war'><br>बिना देरी के, मेजर महार ने बायोनेट चार्ज का आदेश दिया और खुद इसका नेतृत्व किया। इसके बाद हुई भयंकर लड़ाई में मेजर महार और उनके सैनिकों ने बहुत ही बहादुरी से लड़ाई लड़ी, जिसमें 26 दुश्मन सैनिक मारे गए और आठ राइफलें और बहुत सारे हथियार बरामद किए गए।<br><br>दुर्भाग्य से, मेजर महार को लड़ाई के दौरान गंभीर चोटें आईं और उन्होंने अपनी चोटों के कारण दम तोड़ दिया। उनकी बहादुरी और समर्पण के लिए उन्हें वीर चक्र से सम्मानित किया गया, जो भारत के सर्वोच्च वीरता पुरस्कारों में से एक है।<br><br>मेजर जवाहर सिंह महार की कहानी हमें देश के लिए शहीद होने वाले बहादुर सैनिकों की याद दिलाती है। उनकी बहादुरी, नेतृत्व और देश के प्रति समर्पण आज भी हमें प्रेरित करते हैं।</p>"
}
else{
    box.innerHTML="<div class='box' ><div class='dot'></div>English</div>";
    hstory.innerText="Major Jawahar Singh Mahar";
    mhrstory.innerHTML="<p class='mhrstory'>Major Jawahar Singh Mahar was born on December 29, 1921, in the quaint village of Maspati, nestled in Uttarakhand's Pithoragarh district. His father, Shri Joga Singh, raised him with values that would eventually lead him to achieve greatness. From a young age, Mahar harbored a strong desire to serve his nation as an army officer.<br><br><img src='mhr.jpg' alt='Jawahar Singh Mahar' class='images'><br>Mahar's dream took shape when he joined the prestigious 1st Para (Kumaon) battalion as a 2nd Lieutenant on May 29, 1943, at just 21 years old . His exceptional service earned him a promotion to Major in merely five years. Mahar's bravery and leadership were tested during the Indo-Pak War of 1947-48, where he played a crucial role in the defense of Srinagar airfield and the siege of Poonch.<br><br>The story of Major Jawahar Singh Mahar's bravery is a testament to his unwavering courage and dedication to his country.<br><br>In October 1947, the 1st Para (Kumaon) battalion, which Major Mahar was a part of, was deployed to Jammu and Kashmir as part of the first Indian Army formation. The battalion played a crucial role in defending the Srinagar airfield against the invading Pakistani forces.<br><br>A year later, in June 1948, Major Mahar's unit was once again deployed to Jammu and Kashmir to counter the Pakistani forces. On the night of June 15, 1948, a column led by Major Mahar embarked on a mission to link up with another column coming from Rajouri. The plan was to meet at Samhot, but things took a dramatic turn when they encountered an enemy patrol en route.<br><br>Undaunted, Major Mahar cleverly disguised himself as a Pakistani soldier and managed to get his company within 20 yards of the enemy position. However, their guide, a local civilian, inadvertently revealed their true identities, putting Major Mahar and his men in a precarious situation.<br><br><img src='bayonet.jpeg'alt='bayonet war'><br>Without hesitation, Major Mahar ordered a bayonet charge and led the charge himself. The fierce battle that ensued saw Major Mahar and his men fight valiantly, killing 26 enemy soldiers and capturing eight rifles and a large quantity of ammunition.<br><br>Tragically, Major Mahar was severely injured during the battle and succumbed to his wounds. His bravery and selflessness that day earned him the Vir Chakra, one of India's highest gallantry awards.<br><br>Major Jawahar Singh Mahar's story serves as a poignant reminder of the sacrifices made by India's brave soldiers in the line of duty. His courage, leadership, and devotion to his country continue to inspire generations of Indians.</p>";
}
})
